kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  image: kindest/node:latest
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    metadata:
      name: config
    scheduler:
      extraArgs:
        v: "7"
- role: worker
  image: kindest/node:latest
- role: worker
  image: kindest/node:latest
